### PR TITLE
Update Trial Planning Vignette

### LINKED ISSUE #57: Updates to vignette
- [x] Add rpact code to compute sample size for PFS and OS using Schoenfeld:

`library(rpact)

# PFS
pfs_ss <- getSampleSizeSurvival(lambda2 = sum(hsc[s, c("h01", "h02")]), hazardRatio = hr_pfs[s],
                                    accrualTime = 0, accrualIntensity = 500,
                                    maxNumberOfSubjects = 1000, sided = 1, alpha = alphaPFS / 2, beta = 0.2)
pfs_ss <- ceiling(pfs_ss$eventsFixed)
pfs_ss

# OS
os_ss <- getSampleSizeSurvival(lambda2 = sum(hsc[s, c("h01", "h02")]), hazardRatio = os_ahr,
                                accrualTime = 0, accrualIntensity = 500,
                                maxNumberOfSubjects = 2000, sided = 1, alpha = alphaOS / 2, beta = 0.2)
os_ss <- ceiling(os_ss$eventsFixed)
os_ss`

- [x] Use an example from the paper and reproduce numbers in Table 2.
- [x] Add indicator of progress of simulations.
- [x] Computation of AHR: why over many trials? Is this not a deterministic number? --> compute using integrals
- [x] Add function powerIDM and streamline vignette using it.
- [x] For powerIDM: add P(PFS sig), P(OS sig), P(both sig).

### PR DESCRIPTION
**Pull request by holgstr**
Refactoring trial planning vignette:
- a few sentences are rephrased to match wording of new functions
- changes name of powerEmp to empSignificant

### CODE REVIEW

**Comment by holgstr** [comment]
Dear @danielinteractive, I decided to reproduce scenario 2 from the paper for the vignette. However, I cannot reproduce the required OS sample size according to Schoenfeld (732 in the vignette, 708 in the paper). See also the sample code in the linked issue opened by Kaspar.

**Comment by danielinteractive** [comment]
Interesting thanks @holgstr , so is there now new content in the vignette? Or just refactored? I would go first for pure refactoring and then in separate PR add new content.

**Comment by holgstr** [comment]
Hm, I guess I might have misunderstood what „refactoring“ means? 😄 I have substituted the R code with the newly added functions, renamed the powerEmp function to empSignificance, and along the way rephrased some sentences to match the wording of the package/functions better. The only truly new content is the small chunk in the vignette where sample sizes are calculated according to Schoenfeld via rpact. I now see you may prefer me to break up the PR into two smaller ones? Should I do this now or rather keep it in mind going forward?

**Comment by danielinteractive** [comment]
I would say the problematic part of it is new where you cannot reproduce the paper let's split this into separate PR.

**Comment by danielinteractive** [comment]
Sorry about the confusion Kaspars issue refers to the new addition, let's keep this PR to the refactoring I.e. using the new functions you added etc

**Comment by holgstr** [comment]
I have left out the addition of computing the sample sizes via Schoenfeld, so this PR now includes only refactoring + renaming powerEmp to empSignificant.

**Review by danielinteractive — APPROVED** [review]

**Pull request merged**
